## Estudio de Correlacion para proponer Modelo para estimacion % Retencion
## BG = RET_M1
## Elaborado por Charly Moreno

## importando data
MODELO_DATASET_R <- read.delim("~/2. Projectos/Retention Project Rappi/MODELO_DATASET_R.txt")
View(MODELO_DATASET_R)

## acomodando variables

MODELO_DATASET_R$MNT_TOTAL_GMV <- as.numeric(MODELO_DATASET_R$MNT_TOTAL_GMV)
MODELO_DATASET_R$MNT_TOTAL_DESCUENTO <- as.numeric(MODELO_DATASET_R$MNT_TOTAL_DESCUENTO)

MODELO_DATASET_R$MNT_TOTAL_COSTO_ENVIO <- as.numeric(MODELO_DATASET_R$MNT_TOTAL_COSTO_ENVIO)
MODELO_DATASET_R$MNT_TOTAL_COSTO_SERVICIO <- as.numeric(MODELO_DATASET_R$MNT_TOTAL_COSTO_SERVICIO)
MODELO_DATASET_R$MNT_TOTAL_PROPINA <- as.numeric(MODELO_DATASET_R$MNT_TOTAL_PROPINA)

MODELO_DATASET_R$MNT_PROM_GMV <- as.numeric(MODELO_DATASET_R$MNT_PROM_GMV)
MODELO_DATASET_R$MNT_PROM_DESCUENTO <- as.numeric(MODELO_DATASET_R$MNT_PROM_DESCUENTO)
MODELO_DATASET_R$MNT_PROM_COSTO_ENVIO <- as.numeric(MODELO_DATASET_R$MNT_PROM_COSTO_ENVIO)

MODELO_DATASET_R$MNT_PROM_COSTO_SERVICIO <- as.numeric(MODELO_DATASET_R$MNT_PROM_COSTO_SERVICIO)
MODELO_DATASET_R$MNT_PROM_PROM_SERVICIO <- as.numeric(MODELO_DATASET_R$MNT_PROM_PROM_SERVICIO)
MODELO_DATASET_R$MNT_PROM_PROPINA <- as.numeric(MODELO_DATASET_R$MNT_PROM_PROPINA)

MODELO_DATASET_R$EXP_TIEMPO_ESPERA_EFECTIVO_M <- as.numeric(MODELO_DATASET_R$EXP_TIEMPO_ESPERA_EFECTIVO_M)
MODELO_DATASET_R$EXP_TIEMPO_ESPERA_PROMETIDO_M <- as.numeric(MODELO_DATASET_R$EXP_TIEMPO_ESPERA_PROMETIDO_M)

MODELO_DATASET_R$EXP_KPI_TIEMPO_ESPERA <- MODELO_DATASET_R$EXP_TIEMPO_ESPERA_EFECTIVO_M*1.0 / MODELO_DATASET_R$EXP_TIEMPO_ESPERA_PROMETIDO_M*1.0


## realizando analisis de correlacion

corr_mtx <- cor(MODELO_DATASET_R, method="pearson",)

View(corr_mtx)

corr_mtx_1 <- as.data.frame(corr_mtx)

install.packages("openxlsx")
library(openxlsx)

corr_mtx_2 <- write.xlsx(corr_mtx_1,".xlsx")
saveWorkbook(corr_mtx_2, file = "C:/Users/Charly/Documents/2. Projectos/Retention Project Rappi/corr_mtx_2.xlsx", overwrite = TRUE)

## Fin
